spring.application.name=usermanagement
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_db
spring.datasource.username=postgres
spring.datasource.password=D@train20h
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# Spring Security Logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=TRACE
# File Upload
file.upload-dir=uploads
spring.servlet.multipart.enabled=true
